### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ailrun** [CUTE-Lang/miniCUTE#79]
1. Improve the language
    1. Implement a full G-Machine-LLVM compiler
        - [ ] Add data layout
        - [ ] Compile other instructions
        - [ ] Emit executable
    1. Implement some optimizations
        - [ ] DCE
        - [ ] Let merge
        - [ ] Lambda merge (?)
    1. Add more primitives
        - [ ] `if`
        - [ ] `par` (or `parallel`)
        - [ ] `seq` (or `strict`, `sequencial`, ...)
        - [ ] Boolean value (?)
        - [ ] Character or byte value (?)
        - [ ] List or array or vector value
        - [ ] Byte array
    1. Design a type system
        - [ ] User defined type?
        - [ ] Type class
    1. Design a module system
        - [ ] Package alias (?)
        - [ ] `from ... import ... as ...` (?)
        - [ ] Module sectioning? (Ref: Rust, OCaml, Coq)
        - [ ] type class import
1. Create a linter
1. Create lexer/parser generators
1. Replace the compiler language from Haskell to the language

**Comment by Ailrun** [comment]
For type errors, consider to use type inference trace to give users better information.

**Comment by Ailrun** [comment]
Ye, adding tutorial, etc.

**Comment by Ailrun** [comment]
Might be useful (but probably hard): Contextual types

**Comment by Ailrun** [comment]
It might be better to divide this into several sub roadmaps with clear due dates. I will make them tomorrow.
